### ISSUE TITLE
How to use it on misspelled sentence

### ISSUE THREAD

**Issue by Mayank-git** [vuptran/deep-spell-checkr#2]
Please tell me, how to use it for a single misspelled sentence. I don't have the target sentence for it. I just want to test it on single sentence.

I have removed the transform function from evaluate.py but i stuck at line no 42 in evaluate.py (decode_sequences), What to pass in target_input variable in this function.
Thanks in advance.

**Comment by vuptran** [comment]
First, try to set `error_rate = 0.0` in `evaluate.py`, and run it on your misspelled test sentence to see if it works.

Second, take a look at the function `decode_sequences` https://github.com/vuptran/deep-spell-checkr/blob/master/utils.py#L181, and modify it according to your needs. It contains the logic to perform  inference, or sampling strategy, to decode misspelled sentences.

This is as far as I'm able to help you, as you will need to adapt my reference code and pretrained model to your specific use case.
